### PR TITLE
Closes #329 and #340 by amending tylar's PR

### LINKED ISSUE #329: Remove Pagination
[Following this blog post](https://blog.jooq.org/2016/08/10/why-most-programmers-get-pagination-wrong/) @tsujigiri and I briefly discussed this on _Gitter_: 

The SNP index (and I think all the other index pages as well) doesn't actually need the pagination where you can jump to a given page of SNPs (currently there are 236591 pages…). No one uses them. Instead just offering the ⬅️  ➡️  buttons would be good enough. 

This should a) remove clutter from the index pages and b) make things faster.

### PR DESCRIPTION
**Pull request by gedankenstuecke**

### CODE REVIEW

**Comment by philippbayer** [comment]
There are some age-old helpers for this in app/helpers/application_helper.rb which I put there in *2012* to make the pagination look nicer, the methods page_number, previous_or_next_page, and gap, I think these can be deleted? Or are they called somewhere else?

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -9,25 +9,8 @@ def sortable(column, title = nil)
   class BootstrapLinkRenderer < ::WillPaginate::ActionView::LinkRenderer
```
Comment (philippbayer) [inline app/helpers/application_helper.rb]: These two lines can go too - see line 27, there's a double end there

currently it tries to mash page_navigation_links into Bootstrap which breaks
