### PR TITLE
fix fitbit emails, close #310

### LINKED ISSUE #310: `UserMailer#fitbit_dump` is broken
Sidekiq says "ActionView::Template::Error: undefined method `name' for nil:NilClass".

### PR DESCRIPTION
**Pull request by gedankenstuecke**

### CODE REVIEW

File: app/workers/fitbit_dump.rb [hunk 1]
```diff
@@ -56,6 +57,6 @@ def perform(target_address,fitbit_profile_id)
        @fitbit_handle.close
        puts "Saved fibit-date for "
        system("chmod 777 "+::Rails.root.to_s+"/public/data/fitbit/user"+fp.user.id.to_s+"_fitbit_data_"+@time_str.to_s+".csv")
-       UserMailer.fitbit_dump(target_address,"/data/fitbit/user"+fp.user.id.to_s+"_fitbit_data_"+@time_str.to_s+".csv").deliver_later
+       UserMailer.fitbit_dump("/data/fitbit/user"+fp.user.id.to_s+"_fitbit_data_"+@time_str.to_s+".csv",@user).deliver_later
```
Comment (tsujigiri) [inline app/workers/fitbit_dump.rb]: Or, in this case, use string interpolation. :stuck_out_tongue:

File: app/controllers/fitbit_profiles_controller.rb [hunk 2]
```diff
@@ -104,28 +104,28 @@ def show
       end
     end
   end
-  
+
   def dump
     @fitbit_profile = FitbitProfile.find_by_id(params[:id]) || not_found
-    Sidekiq::Client.enqueue(FitbitDump,current_user.email,@fitbit_profile.id)
+    Sidekiq::Client.enqueue(FitbitDump,@fitbit_profile.id,current_user.id)
```
Comment (tsujigiri) [inline app/controllers/fitbit_profiles_controller.rb]: Instead of `Sidekiq::Client.enqueue(FitbitDump, ...)`, you can use `FitbitDump.perform_async(...)`. `enqueue` is somewhat of a legacy API.

File: app/mailers/user_mailer.rb [hunk 3]
```diff
@@ -83,9 +83,10 @@ def no_dump(target_address)
     mail(:subject => "openSNP.org: Sorry, there is no data to be dumped.", :to => target_address)
   end
 
-  def fitbit_dump(target_address,link)
+  def fitbit_dump(link,user)
```
Comment (tsujigiri) [inline app/mailers/user_mailer.rb]: A space after the comma would look nice! :smile:

File: app/workers/fitbit_dump.rb [hunk 4]
```diff
@@ -4,17 +4,18 @@ class FitbitDump
    include Sidekiq::Worker
    sidekiq_options :queue => :fitbit, :retry => 5, :unique => true
 
-   def perform(target_address,fitbit_profile_id)
+   def perform(fitbit_profile_id,user_id)
+     @user = User.find_by_id(user_id)
```
Comment (tsujigiri) [inline app/workers/fitbit_dump.rb]: I don't think you need to load the user here. When you pass it into the mailer, it's going to be serialized automatically (using GlobalID) and loaded again when the mailer is run. Instead, you can just pass along the ID and load the user in the mailer.

File: app/mailers/user_mailer.rb [hunk 5]
```diff
@@ -83,10 +83,10 @@ def no_dump(target_address)
     mail(:subject => "openSNP.org: Sorry, there is no data to be dumped.", :to => target_address)
   end
 
-  def fitbit_dump(link,user)
+  def fitbit_dump(link, user_id)
     @link = link
-		@user = user
-    mail(:subject => "openSNP.org: The Fitbit-data you requested is now ready for download",:to => @user.email)
+		@user = User.find(user_id)
```
Comment (tsujigiri) [inline app/mailers/user_mailer.rb]: Tabs?

**Comment by tsujigiri** [comment]
There's still a lot of places where we are missing a space after a comma. Otherwise it looks good to me. :thumbsup:

File: app/mailers/user_mailer.rb (hunk 5 above)
Comment (gedankenstuecke) [inline app/mailers/user_mailer.rb]: Seems that was one of the cases where Atom screwed up in detecting on whether it should use tabs or spaces, as it usually does this automatically :-)

File: app/mailers/user_mailer.rb [hunk 6]
```diff
@@ -85,7 +85,7 @@ def no_dump(target_address)
 
   def fitbit_dump(link, user_id)
     @link = link
-		@user = User.find(user_id)
+    @user = User.find(user_id)
```
Comment (tsujigiri) [inline app/mailers/user_mailer.rb]: Seems to fit, now. :)

**Comment by gedankenstuecke** [comment]
good to merge now? :)

**Comment by tsujigiri** [comment]
:shipit:

**Comment by gedankenstuecke** [comment]
Always a pleasure to be code-reviewed by @tsujigiri 🎉 ❤️
